language: node_js
node_js:
  - 'node'
env:
  global:
    - EXTENSION_ID=failppjoidijbialknplliogdmabniaf
deploy:
  provider: script
  script: npm run build && npm run update-version && npm run release
  skip_cleanup: true
  on:
      branch: master
      
      # the deployment will be skipped if the last commit doesn't touch the extension's files
      # condition: $(git diff-tree --no-commit-id --name-only -r HEAD | sed -n '/extension\// q 1'; echo $?) = 1
